import { CodeSandbox } from 'assets/icons'
import Head from 'next/head'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen min-h-screen bg-theme-background">
        <div>
          <CodeSandbox />

        </div>
        <div></div>
      </main>
    </div>
  )
}
